# Generated by Django 5.2.4 on 2025-07-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='labtests.gost')),
            ],
        ),
        migrations.AddField(
            model_name='gost',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gosts', to='labtests.material'),
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=50)),
                ('sampling_date', models.DateField()),
                ('received_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('object_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='draft', max_length=20)),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtests.gost')),
                ('indicators', models.ManyToManyField(to='labtests.indicator')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtests.material')),
            ],
        ),
    ]
