# Generated by Django 5.2.4 on 2025-07-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='labtests.gost')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='labtests.mixname'),
        ),
    ]
