# Generated by Django 5.2.4 on 2025-07-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0002_mixname_indicator_mix'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='labtests.material'),
        ),
        migrations.AddField(
            model_name='testsample',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labtests.mixname'),
        ),
    ]
