# Generated by Django 5.2.4 on 2025-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0003_indicator_material_testsample_mix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='mix',
        ),
    ]
