# Generated by Django 4.2.7 on 2025-08-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0008_shchps70458testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crushed32703TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_compound_weight', models.FloatField(blank=True, null=True)),
                ('sieve_2d_weight', models.FloatField(blank=True, null=True)),
                ('sieve_2d_partial', models.FloatField(blank=True, null=True)),
                ('sieve_2d_full', models.FloatField(blank=True, null=True)),
                ('sieve_1_4d_weight', models.FloatField(blank=True, null=True)),
                ('sieve_1_4d_partial', models.FloatField(blank=True, null=True)),
                ('sieve_1_4d_full', models.FloatField(blank=True, null=True)),
                ('sieve_d_weight', models.FloatField(blank=True, null=True)),
                ('sieve_d_partial', models.FloatField(blank=True, null=True)),
                ('sieve_d_full', models.FloatField(blank=True, null=True)),
                ('sieve_d_small_weight', models.FloatField(blank=True, null=True)),
                ('sieve_d_small_partial', models.FloatField(blank=True, null=True)),
                ('sieve_d_small_full', models.FloatField(blank=True, null=True)),
                ('sieve_d_2_weight', models.FloatField(blank=True, null=True)),
                ('sieve_d_2_partial', models.FloatField(blank=True, null=True)),
                ('sieve_d_2_full', models.FloatField(blank=True, null=True)),
                ('mark_type', models.CharField(blank=True, max_length=50, null=True)),
                ('flakiness_weight', models.FloatField(blank=True, null=True)),
                ('flakiness_flaky_weight', models.FloatField(blank=True, null=True)),
                ('flakiness_value', models.FloatField(blank=True, null=True)),
                ('flakiness_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('crushability_type', models.IntegerField(default=0)),
                ('crushability_weight', models.FloatField(blank=True, null=True)),
                ('crushability_after_weight', models.FloatField(blank=True, null=True)),
                ('crushability_value', models.FloatField(blank=True, null=True)),
                ('crushability_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crushed_32703_result', to='labtests.testsample')),
            ],
            options={
                'verbose_name': 'Результат испытания щебня по ГОСТ 32703-2014',
                'verbose_name_plural': 'Результаты испытаний щебня по ГОСТ 32703-2014',
            },
        ),
    ]
