# Generated by Django 4.2.7 on 2025-08-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0011_update_crushed8267testresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_0_density_value',
            new_name='crushability_10_20_after_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_0_empty_weight',
            new_name='crushability_10_20_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_0_volume',
            new_name='crushability_10_20_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_0_weight',
            new_name='crushability_20_40_after_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_1_density_value',
            new_name='crushability_20_40_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_1_empty_weight',
            new_name='crushability_20_40_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_1_volume',
            new_name='crushability_5_10_after_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='bulk_density_1_weight',
            new_name='crushability_5_10_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_0_partial',
            new_name='crushability_5_10_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='crushability_mark_type',
            new_name='crushability_mark',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_0_passes',
            new_name='flakiness_10_20_flaky_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_0_weight',
            new_name='flakiness_10_20_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_1_partial',
            new_name='flakiness_10_20_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_1_passes',
            new_name='flakiness_20_40_flaky_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_1_weight',
            new_name='flakiness_20_40_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_2_partial',
            new_name='flakiness_20_40_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_2_passes',
            new_name='flakiness_40_70_flaky_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_2_weight',
            new_name='flakiness_40_70_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_3_partial',
            new_name='flakiness_40_70_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_3_passes',
            new_name='flakiness_5_10_flaky_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_3_weight',
            new_name='flakiness_5_10_value',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_4_partial',
            new_name='flakiness_5_10_weight',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_4_passes',
            new_name='sieve_10_full',
        ),
        migrations.RenameField(
            model_name='crushed8267testresult',
            old_name='partition_4_weight',
            new_name='sieve_10_partial',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='average_density_dried_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='average_density_empty_basket_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='average_density_value',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='average_density_weight_in_air',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='average_density_weight_in_water',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='bulk_density_average',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='crushability_after_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='crushability_value',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='crushability_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='flakiness_flaky_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='flakiness_mark_type',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='flakiness_value',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='flakiness_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='weak_rock_content',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='weak_rock_initial_weight',
        ),
        migrations.RemoveField(
            model_name='crushed8267testresult',
            name='weak_rock_weight',
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='crushability_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя дробимость, %'),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='flakiness_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя лещадность, %'),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='flakiness_group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа по лещадности'),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='fraction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_10_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_1_25_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_1_25_partial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_1_25_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_20_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_20_partial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_20_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_2_5_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_2_5_partial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_2_5_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_40_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_40_partial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_40_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_5_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_5_partial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_5_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_70_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_70_partial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crushed8267testresult',
            name='sieve_70_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crushed8267testresult',
            name='clay_initial_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса пробы, г'),
        ),
        migrations.AlterField(
            model_name='crushed8267testresult',
            name='clay_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса глины в комках, г'),
        ),
        migrations.AlterField(
            model_name='crushed8267testresult',
            name='crushability_type',
            field=models.IntegerField(default=0, verbose_name='Тип породы'),
        ),
        migrations.AlterField(
            model_name='crushed8267testresult',
            name='dust_after_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса после отмучивания, г'),
        ),
        migrations.AlterField(
            model_name='crushed8267testresult',
            name='dust_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Содержание п/г частиц, %'),
        ),
        migrations.AlterField(
            model_name='crushed8267testresult',
            name='dust_initial_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса начальная, г'),
        ),
    ]
